### PR TITLE
Tracing with puffin!

### PR DESCRIPTION
**Pull request by siedentop**
Amazing framework. Thanks a lot to the the puffin developers. Thanks to @emilk for [helping out](https://github.com/EmbarkStudios/puffin/issues/46)

How to use it is described in the Readme: 

```bash
cargo run --example create_test_file
cargo run --features trace -- binocle_test_file
```

In another terminal run:

```bash
cargo install puffin_viewer
puffin_viewer --url 127.0.0.1:8585
```

### CODE REVIEW

**Comment by siedentop** [comment]
FYI: @sharkdp

**Comment by siedentop** [comment]
The build failure is persistent also on my forked repo: https://github.com/siedentop/binocle/runs/4194742703?check_suite_focus=true

Issue is on "windows-2019 (x86_64-pc-windows-gnu)", and `zstd` custom build command is failing. 

I would like to just disable the tracing feature for this platform then.

**Comment by sharkdp** [comment]
Thank you for making me aware of this framework. This sounds really helpful. However, I'd rather not include tracing support by default here in this project - even if it's hidden behind a feature flag. I'd would try to avoid having to maintain this in the future. This PR/branch is still valuable for documentation purposes though!

Remark: if you want to make code like this optional, you can/should also make the necessary dependencies optional: https://doc.rust-lang.org/cargo/reference/features.html#optional-dependencies

**Comment by siedentop** [comment]
Sounds good to me!

**Pull request closed without merging**
